export const servicesInfos = [
    {
        "id" : "1",
        "name" : "Frontend Developper",
        "img" : "/ServiceImages/frontEnd.jpeg",
        "description" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
        "location" : "Yaounde/Biyemassi",
        "salary" : "200$",
    },
    
    {
        "id" : "2",
        "name" : "Backend Developper",
        "img" : "/ServiceImages/back.jpeg",
        "description" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
        "location" : "Yaounde/Tongolo",
        "salary" : "350$",
    },
    {
        "id" : "3",
        "name" : " Digital marketer ",
        "img" : "/ServiceImages/marketer.jpeg",
        "description" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
        "location" : "Douala/Logpom",
        "salary" : "300$",
    },
    {
        "id" : "4",
        "name" : "Home teacher",
        "img" : "/ServiceImages/teacher.jpeg",
        "description" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
        "location" : "Yaounde/Biiteng",
        "salary" : "90$",
    },
    {
        "id" : "5",
        "name" : "Carpenter",
        "img" : "/ServiceImages/carpenter.jpeg",
        "description" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
        "location" : "Douala/Bonaberi",
        "salary" : "100$",
    },
    {
        "id" : "6",
        "name" : "Driver",
        "img" : "/ServiceImages/driver.jpeg",
        "description" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
        "location" : "Yaounde/Omnisport",
        "salary" : "150$",
    },
    {
        "id" : "7",
        "name" : "Graphic Designer",
        "img" : "/ServiceImages/designer.jpeg",
        "description" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
        "location" : "Yaounde/Damas",
        "salary" : "300$",
    },
    {
        "id" : "8",
        "name" : " Agricultural Engineer",
        "img" : "/ServiceImages/agricEng.jpeg",
        "description" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
        "location" : "Bamendjou",
        "salary" : "1200$",
    },
    {
        "id" : "9",
        "name" : "Good Student",
        "img" : "/ServiceImages/student.jpeg",
        "description" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
        "location" : "Yaounde/Coron",
        "salary" : "2000$",
    },

] 